###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "passwort": "passwordDddddddddddd!123"
}

###
POST http://localhost:5000/user
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "passwort": "passwordDddddddddddd!123"
}

###
GET http://localhost:5000/user

###
GET http://localhost:5000/user/1

###
DELETE  http://localhost:5000/user/1

###
PUT http://localhost:5000/user/1
Content-Type: application/json

{
  "firstName": "Johnnew2",
  "lastName": "Doenew2",
}

###
GET http://localhost:5000/user/session_data

###
POST http://localhost:5000/user/logout
