@baseURL = http://localhost:5000/user

###
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "passwort": "Password!123456789"
}

###
POST {{baseURL}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "passwort": "passwordDddddddddddd!123"
}

###
GET {{baseURL}}

###
GET {{baseURL}}/1

###
DELETE  {{baseURL}}/1

###
PUT {{baseURL}}/2
Content-Type: application/json

{
  "firstName": "Johnnew2",
  "lastName": "Doenew2"
}

###
GET {{baseURL}}/session_data

###
POST {{baseURL}}/logout
